# Generated by Django 4.2.9 on 2026-03-30 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0003_nmapscandb_is_vulners"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="niktovulndb",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="niktovulndb",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="niktovulndb",
            name="project",
        ),
        migrations.RemoveField(
            model_name="niktovulndb",
            name="updated_by",
        ),
        migrations.DeleteModel(
            name="NiktoResultDb",
        ),
        migrations.DeleteModel(
            name="NiktoVulnDb",
        ),
    ]
